[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv_.*
  | _build
  | buck-out
  | build
  | dist
  | node_modules
  | frontend
)/
'''

[tool.ruff]
line-length = 100
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "venv*",
    "package*",
    "**/test*",
]

[tool.ruff.lint]
ignore = [
    "E203",  # Whitespace before ':'
    "E266",  # Too many leading '#'
    "E501",  # Line too long (82 > 79 characters)
    "F403",  # 'from module import *' used; unable to detect undefined names
    "F401",  # Module imported but unused
    "E722",  # do not use bare except (viewsに存在、不要か検討の余地あり)
    "F811",  # Redefinition of unused name from line n (settingsに存在、不要か検討の余地あり)
    "E731",  # Do not assign a lambda expression, use a def
    "F821",  # Undefined name name
]
select = [
    "B",    # flake8-bugbear
    "C",    # flake8-comprehensions
    "E",    # pycodestyle errors
    "F",    # flake8 pyflakes
    "W",    # pycodestyle warnings
    "B9",   # flake8-blind-except
]

[tool.mypy]
plugins = ["pydantic.mypy"]
follow_imports = "skip"

[[tool.mypy.overrides]]
module = ["boto3", "boto3.*"]
ignore_missing_imports = true
